### ISSUE TITLE
Share some photos ?

### ISSUE THREAD

**Issue by chrigui** [AfdhalAtiffTan/FYP_SmartWinch#11]
Hello
Thank you for sharing this project.
do you have photos or videos to share about this project, please ?

Many Thanks.

**Comment by chrigui** [comment]
Found it! sorry
https://afdhalatifftan.github.io/ProjectPresentation/

**Comment by AfdhalAtiffTan** [comment]
https://youtu.be/p0hat2Mh-QQ
